# This is a basic workflow that is manually triggered

name: Run unittests

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    branches:
      - master
      - 'releases/**'
  push:
    branches:
      - master
      - 'releases/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  run_unittests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2.4.2
      with:
        repository: ${{ github.repository }}
      
    # Runs a single command using the runners shell
    - name: Run unittests
      run: echo "Hello ${{ github.event.inputs.name }}" && python3 -m unittest tests/test_salary_calc_unit.py
      
